version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: dataset_catalog_db
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: dataset_catalog
    volumes:
      - mongodb_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - dataset_catalog_network

  api:
    build: .
    container_name: dataset_catalog_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=dataset_catalog
      - FLASK_DEBUG=false
      - SECRET_KEY=your-secret-key
      - ITEMS_PER_PAGE=20
    depends_on:
      - mongodb
    networks:
      - dataset_catalog_network
    volumes:
      - ./logs:/app/logs

  test:
    build: .
    container_name: dataset_catalog_test
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB=dataset_catalog_test
      - FLASK_DEBUG=true
      - SECRET_KEY=test-secret-key
      - ITEMS_PER_PAGE=20
    depends_on:
      - mongodb
    networks:
      - dataset_catalog_network
    working_dir: /app
    command: python -m pytest -v
    profiles:
      - test 

  mongo-express:
    image: mongo-express:1.0.0
    container_name: dataset_catalog_admin
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - dataset_catalog_network

volumes:
  mongodb_data:
    driver: local

networks:
  dataset_catalog_network:
    driver: bridge
